# Generated by Django 5.0.7 on 2024-08-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='APTGroup',
        ),
    ]
