# Generated by Django 5.0.7 on 2024-08-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_rename_group_aptgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptgroup',
            options={'verbose_name': 'APT Group', 'verbose_name_plural': 'APT Groups'},
        ),
    ]
