# Generated by Django 5.0.7 on 2024-07-19 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.CharField(help_text="MITRE ID of the technique (ie. 'attack-pattern-xxxxx').", max_length=120, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, help_text='A name for the technique.', max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the technique.', null=True)),
                ('data_sources', models.TextField(blank=True, help_text='Technique data sources.', null=True)),
                ('kill_chain_phases', models.TextField(blank=True, help_text='Technique platforms.', null=True)),
                ('url', models.TextField(blank=True, help_text='Technique URL, comma separated.', null=True)),
                ('detection', models.TextField(blank=True, help_text='Technique detection information.', null=True)),
                ('permissions_required', models.TextField(blank=True, help_text='Permissions required for this technique, comma separated.', null=True)),
                ('platforms', models.TextField(blank=True, help_text='Technique platforms, comma separated.', null=True)),
                ('subtechniques', models.ManyToManyField(blank=True, help_text='Selection of techniques connected to this tactic.', to='knowledgebase.technique')),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
            },
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.CharField(help_text="MITRE ID of the tactic (ie. 'x-mitre-tactic--xxxxxxx').", max_length=120, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, help_text='A name for the tactic.', max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the tactic.', null=True)),
                ('url', models.TextField(blank=True, help_text='Tactic URL, comma separated.', null=True)),
                ('techniques', models.ManyToManyField(blank=True, help_text='Selection of techniques connected to this tactic.', related_name='tactictechnique', to='knowledgebase.technique')),
            ],
            options={
                'verbose_name': 'Tactic',
                'verbose_name_plural': 'Tactics',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(help_text="MITRE ID of the group (ie. 'intrusion-set-xxx').", max_length=120, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, help_text='A name for the game.', max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the group.', null=True)),
                ('aliases', models.TextField(blank=True, help_text='Group aliases, comma separated.', null=True)),
                ('techniques', models.ManyToManyField(blank=True, help_text='Selection of techniques used by this group.', related_name='grouptechnique', to='knowledgebase.technique')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
