# Generated by Django 5.0.7 on 2024-08-04 11:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3cdc419d-d7da-4407-ba27-a03f89319552'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, help_text='The name of the company.', max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the company.', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='companygroup', to='auth.group')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8466aa82-752b-4c90-9ab1-adf7304ab8e1'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField(default=uuid.UUID('52f6d15e-23cf-4fc2-aba1-be0160075dd0'), help_text='Unique billing code.', unique=True)),
                ('name', models.CharField(blank=True, help_text='The name associated to this billing information.', max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this billing method.', null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.company')),
            ],
            options={
                'verbose_name': 'BillingInfo',
                'verbose_name_plural': 'BillingInfo',
            },
        ),
    ]
