# Generated by Django 5.0.7 on 2024-08-04 17:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('web', '0001_initial'), ('web', '0002_company_active_company_url_alter_company_created_at_and_more'), ('web', '0003_alter_billing_options_subscription_subscription_and_more'), ('web', '0004_subscription_total_tokens_subscription_trial_days_and_more'), ('web', '0005_remove_subscription_total_tokens_billing_old_company_and_more'), ('web', '0006_alter_billing_code_alter_billing_description_and_more'), ('web', '0007_remove_company_group_alter_billing_code_and_more')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('99b1ef7d-ab23-45e7-a32a-2b2d0d7f341c'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Company XYZ', help_text='The name of the company.', max_length=80)),
                ('description', models.TextField(blank=True, help_text='Description of the company.', null=True)),
                ('active', models.BooleanField(default=True, help_text='If this company is active or not. When disabled, no account related to this company can login.')),
                ('url', models.URLField(blank=True, help_text='(optional) Company URL field.', null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4176edd7-6e73-4969-ad42-a6331de25a20'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField(default=uuid.UUID('61f367fb-e492-44d0-9e53-12719fed9d1d'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True)),
                ('name', models.CharField(default='main', help_text='A name associated to this billing information.', max_length=80)),
                ('description', models.TextField(blank=True, help_text='Optional description of this billing information.', null=True)),
                ('active', models.BooleanField(default=False, help_text='If this billing information is active or not.')),
                ('company', models.ForeignKey(help_text='Which company this billing information is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billinginfocompany', to='web.company')),
                ('old_company', models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from. <b>Will be overwritten automatically</b>.', max_length=80)),
            ],
            options={
                'verbose_name': 'Billing record',
                'verbose_name_plural': 'Billing records',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('63d90445-be3a-4670-900e-79e35fe10794'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField(default=uuid.UUID('65f2fe8e-fe6d-43fe-bc8c-252eda9fbd6a'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True)),
                ('name', models.CharField(default='main', help_text='A name associated to this billing information.', max_length=80)),
                ('description', models.TextField(blank=True, help_text='Optional description of this billing method.', null=True)),
                ('active', models.BooleanField(default=False, help_text='If this subscription is active or not.')),
                ('company', models.ForeignKey(help_text='Which company this subscription is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptioncompany', to='web.company')),
                ('subscription', models.CharField(choices=[('customer-trial', 'customer-trial'), ('customer-token-based', 'customer-token-based'), ('customer-subscription-small', 'customer-subscription-small'), ('customer-subscription-medium', 'customer-subscription-medium'), ('customer-subscription-large', 'customer-subscription-large'), ('customer-subscription-enterprise', 'customer-subscription-enterprise')], default='none', help_text='The type of the subscription. Fields below will be used differently based on the selected subscription.', max_length=60)),
                ('tokens', models.FloatField(default=0, help_text='Current amount of tokens for this subscription. <b>Will only be reset when no tokens left and a topup is bought</b>. <br><i>Used only for token-based subscriptions</i>.')),
                ('trial_days', models.IntegerField(default=0, help_text='Amount of days the trial should last. <b>Used only for trial subscriptions</b>.')),
                ('trial_since', models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start date. <b>Used only for trial subscriptions</b>.')),
                ('hidden', models.BooleanField(default=False, help_text="If this subscription should be hidden from the customer. Used to 'remove' old subscriptions which are still useful for subscription/billing management.")),
                ('monthly_tokens', models.FloatField(default=0, help_text='Amount of monthly tokens. <b>Used for monthly subscriptions</b>.')),
                ('old_company', models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from. <br><b>Will be overwritten automatically</b>.', max_length=80)),
                ('total_tokens_bought', models.FloatField(default=0, help_text='Total amount of tokens bought, <b>incremented only at each topup</b>. <br><i>Used only for token-based subscriptions</i>.')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, help_text='The company the user is part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercompany', to='web.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
