# Generated by Django 5.0.7 on 2024-08-04 11:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, help_text='If this company is active or not. When disabled, no account related to this company can login.'),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, help_text='(optional) Company URL field.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.ForeignKey(help_text='Which group this company is connected to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='companygroup', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2c881f7-63a2-44f1-b0ed-db665afbc5f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8d729c51-9bb0-4d00-944f-a08e99b55cdd'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField(default=uuid.UUID('c4666e0e-8112-4e71-9e90-18e1fdd6df7a'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True)),
                ('name', models.CharField(blank=True, help_text='The name associated to this billing information.', max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='(optional) Description of this billing information.', null=True)),
                ('active', models.BooleanField(default=False, help_text='If this billing information is active or not.')),
                ('company', models.ForeignKey(help_text='Which company this billing information is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billinginfocompany', to='web.company')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billing',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('88226481-6417-4109-88d5-e7c149191519'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField(default=uuid.UUID('3583a0e1-0009-4f30-9c69-dfc651ed4617'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True)),
                ('name', models.CharField(blank=True, help_text='The name associated to this billing information.', max_length=80, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this billing method.', null=True)),
                ('active', models.BooleanField(default=False, help_text='If this subscription is active or not.')),
                ('company', models.ForeignKey(help_text='Which company this subscription is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptioncompany', to='web.company')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
