# Generated by Django 5.0.7 on 2024-08-04 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_company_active_company_url_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Billing record', 'verbose_name_plural': 'Billing records'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(choices=[('customer-trial', 'customer-trial'), ('customer-token-based', 'customer-token-based'), ('customer-subscription-small', 'customer-subscription-small'), ('customer-subscription-medium', 'customer-subscription-medium'), ('customer-subscription-large', 'customer-subscription-large'), ('customer-subscription-enterprise', 'customer-subscription-enterprise')], default='none', help_text='This field is set automatically when None during saving but can be overwritten manually.', max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens',
            field=models.FloatField(blank=True, default='0', help_text='Amount of tokens left for this subscription.'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.UUIDField(default=uuid.UUID('38e9388b-5236-40e4-9787-40c5f274f2a0'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71a2499e-4aac-4731-9cd2-b222231defe5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(default='main', help_text='The name associated to this billing information.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cbbdb15e-7404-4c4a-9658-fd8f88dba1c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Company name', help_text='The name of the company.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.UUIDField(default=uuid.UUID('36816b5a-ff5f-4dbf-91aa-07bd6d5a7638'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49f33c0a-43be-491e-9a50-f63ca0956714'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='main', help_text='The name associated to this billing information.', max_length=80, unique=True),
        ),
    ]
