# Generated by Django 5.0.7 on 2024-08-04 12:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_billing_options_subscription_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_tokens',
            field=models.FloatField(blank=True, default='0', help_text='Amount of tokens left for this subscription.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_days',
            field=models.IntegerField(default=7, help_text='Amount of days the trial should last. Only used when trial is selected via the subscription field.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_since',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start date. Only used when trial is selected via the subscription field.'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.UUIDField(default=uuid.UUID('15367b29-de51-4f32-94d2-5e318c222bf1'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60395761-a97b-40ee-998e-ead6718e2759'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(default='main', help_text='The name associated to this billing information.', max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26467a29-67bc-4f57-982f-4eeeea0e2654'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Company name', help_text='The name of the company.', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.UUIDField(default=uuid.UUID('0cdedb90-80f5-42c8-9774-20ca18ac4a66'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59d2b778-2dc9-46b0-812f-624af8b7efd8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='main', help_text='The name associated to this billing information.', max_length=80),
        ),
    ]
