# Generated by Django 5.0.7 on 2024-08-04 12:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_subscription_total_tokens_subscription_trial_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='total_tokens',
        ),
        migrations.AddField(
            model_name='billing',
            name='old_company',
            field=models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from.', max_length=80),
        ),
        migrations.AddField(
            model_name='subscription',
            name='hidden',
            field=models.BooleanField(default=False, help_text="If this subscription should be hidden from the customer. Used to 'remove' old trial subscriptions."),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_tokens',
            field=models.FloatField(default=0, help_text='Amount of monthly tokens. Used for monthly subscriptions.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='old_company',
            field=models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from.', max_length=80),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_tokens_bought',
            field=models.FloatField(default=0, help_text='Total amount of tokens bought. <b>Used only for token-based subscriptions</b>.'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.UUIDField(default=uuid.UUID('94a9920a-39f7-4144-b4c6-44fa74900a1b'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9902b13d-9c57-4de5-8d2a-2d6825a8b02c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc2ae9b4-14ba-40ac-a3f4-7d19cad6b6d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.UUIDField(default=uuid.UUID('4349ba1c-8379-4751-af86-a808e7e90055'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5534229-8f9e-4b23-9633-ee9ab7ddce2d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tokens',
            field=models.FloatField(default=0, help_text='Current amount of tokens for this subscription. <b>Only used when token-based is selected via the subscription field</b>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Amount of days the trial should last. <b>Only used when trial is selected via the subscription field</b>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_since',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start date. <b>Only used when trial is selected via the subscription field</b>.'),
        ),
    ]
