# Generated by Django 5.0.7 on 2024-08-04 12:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0005_remove_subscription_total_tokens_billing_old_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.UUIDField(default=uuid.UUID('5faf64ea-c5a7-4c84-965b-54691a9402eb'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this billing information.', null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc6ac8d3-121f-4ce1-b4b6-a519f8764b75'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(default='main', help_text='A name associated to this billing information.', max_length=80),
        ),
        migrations.AlterField(
            model_name='billing',
            name='old_company',
            field=models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from. <b>Will be overwritten automatically</b>.', max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.ForeignKey(help_text='Which Django group this company is connected to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='companygroup', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab586f1d-3860-492a-9458-6cc7d96c2791'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Company XYZ', help_text='The name of the company.', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.UUIDField(default=uuid.UUID('09c9d6ff-8f60-4d8c-b71f-2267fa15dcb6'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='hidden',
            field=models.BooleanField(default=False, help_text="If this subscription should be hidden from the customer. Used to 'remove' old subscriptions which are still useful for subscription/billing management."),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a777dddb-8bb0-435c-affb-467ea7e8da37'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_tokens',
            field=models.FloatField(default=0, help_text='Amount of monthly tokens. <b>Used for monthly subscriptions</b>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='main', help_text='A name associated to this billing information.', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='old_company',
            field=models.CharField(blank=True, help_text='The name of the company. Used as backup for when the company were to be removed and we need to know where this subscription was from. <br><b>Will be overwritten automatically</b>.', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(choices=[('customer-trial', 'customer-trial'), ('customer-token-based', 'customer-token-based'), ('customer-subscription-small', 'customer-subscription-small'), ('customer-subscription-medium', 'customer-subscription-medium'), ('customer-subscription-large', 'customer-subscription-large'), ('customer-subscription-enterprise', 'customer-subscription-enterprise')], default='none', help_text='The type of the subscription. Fields below will be used differently based on the selected subscription.', max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tokens',
            field=models.FloatField(default=0, help_text='Current amount of tokens for this subscription. <b>Will only be reset when no tokens left and a topup is bought</b>. <br><i>Used only for token-based subscriptions</i>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_tokens_bought',
            field=models.FloatField(default=0, help_text='Total amount of tokens bought, <b>incremented only at each topup</b>. <br><i>Used only for token-based subscriptions</i>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Amount of days the trial should last. <b>Used only for trial subscriptions</b>.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_since',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start date. <b>Used only for trial subscriptions</b>.'),
        ),
    ]
