# Generated by Django 5.0.7 on 2024-08-04 17:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0006_alter_billing_code_alter_billing_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='group',
        ),
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.UUIDField(default=uuid.UUID('61f367fb-e492-44d0-9e53-12719fed9d1d'), editable=False, help_text='Unique billing code. Used to identify billing during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4176edd7-6e73-4969-ad42-a6331de25a20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99b1ef7d-ab23-45e7-a32a-2b2d0d7f341c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.UUIDField(default=uuid.UUID('65f2fe8e-fe6d-43fe-bc8c-252eda9fbd6a'), editable=False, help_text='Unique subscription code. Used to identify subscription during support.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63d90445-be3a-4670-900e-79e35fe10794'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, help_text='The company the user is part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercompany', to='web.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
